sudo: false
language: cpp
compiler:
  - gcc
#  - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - openmpi-bin 
    - libopenmpi-dev
#    - clang
notifications:
  email:
    recipients:
      - sharker81@gmail.com
    on_success: change
    on_failure: always
before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - PREFIX=$HOME/.local
  - export PATH=$PREFIX/bin:$PATH
install:
  - pip install cpp-coveralls --user `whoami`
  - ./.install/boost.sh thread,system,serialization,chrono
  - ./.install/delegator.sh
script: 
  - ./install.sh --build=Debug
  - coveralls -E ".*examples.*" -E ".*tools.*" -E ".*lib.*" -E ".*usr.*" -E ".*boost.*" --gcov-options '\-lp' --gcov /usr/bin/gcov-4.8
